spring:
  datasource:
    url: jdbc:mysql://sql10.freemysqlhosting.net:3306/sql10187921
    username: sql10187921
    password: XhcNnlbNGJ
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://sql10.freemysqlhosting.net:3306/sql10187921
    username: sql10187921
    password: XhcNnlbNGJ
    initialize: true